### ISSUE TITLE
How to timeout long requests that do not respond / throw error?

### ISSUE THREAD

**Issue by solserer-labs** [transitive-bullshit/chatgpt-api#16]
Responses sometimes hang with nothing returning. This could be due to increasing server load or some rate limiting features.

Is it possible to add a timeout/throw error for each request?

**Comment by transitive-bullshit** [comment]
This is definitely a good idea worth considering.

In my Twitter bot, I'm wrapping the call to `ChatGPT.getMessage` with [p-timeout](https://github.com/sindresorhus/p-timeout). Example here: https://github.com/transitive-bullshit/chatgpt-twitter-bot/blob/main/src/respond-to-new-mentions.ts#L378-L381

I think the real question is whether or not it makes sense to have this built into the package or just an example of how to do it on top of the package.

I think lot of the slow requests are due to ChatGPT rate limiting and massive server load on their side of things. I did a bunch of testing last night w/ the browser version vs the REST API version and couldn't discern any significant differences in response times. The API-based one just seemed to take a lot longer since you couldn't view the partial results along the way.

One option is to use the optional `onProgress` parameter to log partial results so you know it's working along the way.

Thoughts?

**Comment by abi** [comment]
Tangentially, I think it would be nice to have a separate streaming API. For lots of applications, showing partial results as they come in is a nice way to reduce perceived latency to the user. I'm happy to work on it if that might be something you'd want to add.

**Comment by solserer-labs** [comment]
> 

Yeah tbh probably a better idea to keep a good separation of concerns and keep the timeout logic outside of the package and just show an example of how to do it. Cheers for the suggestion.

**Comment by transitive-bullshit** [comment]
Agreed on streaming support @abi.

**Comment by transitive-bullshit** [comment]
Here's an example for how to do this:

```ts
import pTimeout from 'p-timeout'
import { ChatGPTAPI } from 'chatgpt'

const chatgpt = new ChatGPTAPI({ sessionToken: process.env.SESSION_TOKEN })

const threeMinutesMs = 3 * 60 * 1000
const response = await pTimeout(
  chatgpt.sendMessage("Example prompt"),
  {
    milliseconds: threeMinutesMs,
    message: 'ChatGPT timed out waiting for response'
  }
)
```
