### ISSUE TITLE
Save Session Token on Development

### ISSUE THREAD

**Issue by danielehrhardt** [transitive-bullshit/chatgpt-api#162]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Verify resrictions

- [X] I verify that I've double-checked all of the restrictions.

### Environment details

Node 19.2.0
Windows 11

### Link to the code that reproduces this issue

-

### Describe the Bug

It would be nice to save all Token at least for 1 hour or something because when you're developing in typescript and rerun the script all the time the login need to be done every time so it would be nice to store the tokens with a lifetime to a file and check that file on restart. 

This is not a Bug this is a Feature Request. 

### To Reproduce

-

### Expected Behavior

-

**Comment by transitive-bullshit** [comment]
Hey @danielehrhardt, thanks for the feature request.

Here are a few ideas on how we could improve this flow:

1. We could use a persistent chrome session tied to each account email, so when you open a browser with the same email, it will have the same cookies and everything.
2. Generally, this package is meant to be used from within another program instead of running the demo over and over. So the ideal workflow is to embed the package inside of an app that listens for events and responds one-by-one. This way you only login once and then just respond to events as they come instead of having to login for every event.

I would recommend that you go with number 2 for now as that's the intended usage. I'll consider adding support for number 1.

**Comment by danielehrhardt** [comment]
i tried it out but it does not work
