### ISSUE TITLE
Can I have multiple instances in parallel?

### ISSUE THREAD

**Issue by czzonet** [transitive-bullshit/chatgpt-api#170]
### Describe the feature

Very useful project, tough but running successfully.

Can I have multiple instances in parallel? Because it takes more than 1 minute for the server to complete the response.

**Comment by czzonet** [comment]
I suddenly realized that using two accounts shouldn't conflict, right?

**Comment by timmsGithub** [comment]
U can use proxies and different accounts at once.

Just init them with new ChatGPTAPIBrowser() and put all instances in one array.

**Comment by transitive-bullshit** [comment]
Yes; I'm currently running a large pool of accounts using https://github.com/transitive-bullshit/chatgpt-twitter-bot/blob/main/src/chatgpt-api-pool.ts

Also note that I would recommend initializing the session once and then using that session for as long as possible to respond to messages, instead of re-initializing the session every time.

**Comment by czzonet** [comment]
> Yes; I'm currently running a large pool of accounts using https://github.com/transitive-bullshit/chatgpt-twitter-bot/blob/main/src/chatgpt-api-pool.ts
> 
> Also note that I would recommend initializing the session once and then using that session for as long as possible to respond to messages, instead of re-initializing the session every time.

Great, I saw that you used 'p-map' to return an array of account instances, I tried similarly with two accounts and it worked.
