### ISSUE TITLE
Running ChatGPT-API inside an ubuntu docker

### ISSUE THREAD

**Issue by vaibhavholani** [transitive-bullshit/chatgpt-api#177]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Docker Container
Ubuntu 22.04.1
Node.js v18.0.0

## Error
TimeoutError: Waiting for selector `#password` failed: Waiting failed: 120000ms exceeded

## Running Command
```xvfb-run --auto-servernum node app.js```

## Help
Since I am running this without a gui, I believe it is not able to bypass the captcha. If someone else has made it work in this environment, please let me know. 

Any suggestions are appreciated!

**Comment by Tpgainz** [comment]
Captcha gone wrong firend !

**Comment by lukasvdberk** [comment]
(not a maintainer)

I am also unable to bypass the capatcha as well without using Docker. This has nothing todo that you do not have a gui in Docker. You can however setup a headless browser in Docker to run puppeteer with that instead of a browser with a gui https://www.toptal.com/puppeteer/headless-browser-puppeteer-tutorial . However if the browser is headless you it does not have a GUI you can interact with and you can not complete the captcha as human.

Hoped I could help!

**Comment by transitive-bullshit** [comment]
@vaibhavholani Are you setting up a CAPTCHA provider to automatically bypass captchas? Double-check this section of the readme https://github.com/transitive-bullshit/chatgpt-api#captchas

I know there other devs on discord who have gotten this working with `xvfb`, so it's definitely possible, though it may require some daemonization and/or retry logic.

**Comment by yueyan-zm** [comment]
I have tried to use the x11 forwarding method to connect, and the intermediate verification can be successful through my own manual verification. But because my server configuration is too low, I usually get the session_token and cf_clearance. This should be possible, but it needs to be replaced manually frequently.

**Comment by vaibhavholani** [comment]
Hey, yes seems to be working with a nopecha key, I had missed that part. Thanks.
