### ISSUE TITLE
Can't get nopecha to work

### ISSUE THREAD

**Issue by Glowin** [transitive-bullshit/chatgpt-api#183]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node: v18.12.1

browser version: 108.0.5359.98

OS version: Mac OS Big Sur 11.7 (20G817)

### Describe the Bug
I had put .env file to the root of project.
and add key to .env file like : NOPECHA_KEY='I-XXXXXXXXX'
The script was executed as usual, but the CAPTCHA was not executed automatically, as shown in the video below.

https://user-images.githubusercontent.com/1147941/208948411-355eab3e-fbac-46ac-b6bb-5deaa4ff1893.mp4

**Comment by transitive-bullshit** [comment]
Thanks for creating the issue and including a video.

A few follow-up questions:

1. Does it always not work or just some of the time?
2. Can you paste in the full console output of running the demo? We log some additional things depending on nopecha.

At the start of the video, I'm not seeing the nopecha initialization. This may be due to just not recording it or it may not be getting initialized correctly.

**Comment by kraj011** [comment]
Hey!
Getting the same issue.
I have no logs being outputted whatsover, so I think nopecha might not be initializing properly(?). 
Lmk if there's any info I can provide to get this fixed!

**Comment by Glowin** [comment]
@transitive-bullshit 

1. always not work
2. no output about nopecha in console

Like @kraj011 reply, nopecha may not be initializing right. Following the solution @kraj011  just provided, I have implemented the nopecha functionality.

**Comment by danielehrhardt** [comment]
With this change, you can pass the key as variable https://github.com/transitive-bullshit/chatgpt-api/pull/189

**Comment by transitive-bullshit** [comment]
Just released a bunch of nopecha fixes including @danielehrhardt's PRs. Hopefully this will resolve your problems.
