### ISSUE TITLE
Failed to Deploy on render.com

### ISSUE THREAD

**Issue by Moh-Adel-Aly** [transitive-bullshit/chatgpt-api#237]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node.js v18.12.1

### Describe the Bug

So everything works locally, and I have no issues whatsoever. The issue is when I try to deploy the service to render.com.

Puppeteer is unable to create a browser instance while deploying.

1- I have the latest Puppeteer installed
2- I also tried Puppeteer-core

I still get the same error which is:

![image](https://user-images.githubusercontent.com/87696510/211149108-82648bb3-851d-4a2b-ba1e-f9e2111f6108.png)

Is it possible to make Puppeteer run some sort of headless chrome, and would that maybe fix the issue?

Please suggest me an approach to work with.

Thanks!

**Comment by Moh-Adel-Aly** [comment]
Do you know any online service other than render.com that is sure to work?

**Comment by christophebe** [comment]
All the online services that support docker.

More help here for puppeteer on docker  : https://www.howtogeek.com/devops/how-to-run-puppeteer-and-headless-chrome-in-a-docker-container/

**Comment by Ayush-k-Shukla** [comment]
@Moh-Adel-Aly 
To run a headless puppeteer you can give the `headless` variable true while launching.
`const browser = await puppeteer.launch({ headless: true});`

**Comment by transitive-bullshit** [comment]
You can also set the `PUPPETEER_EXECUTABLE_PATH` environment variable to override the path puppeteer uses.

Other devs have gotten this working, though you may need to use `xvfb` and possibly docker to get the headful version working. I haven't tested the headless version – you'll have to edit the source of this package if you want to try running it headless. The reason we don't run it headless by default is because Cloudflare's protections can detect this and make it harder to access.
