### ISSUE TITLE
Chrome won't minimize

### ISSUE THREAD

**Issue by B1LDER** [transitive-bullshit/chatgpt-api#251]
### Describe the feature

So, here's the issue:

I'm runring ChatGPTAPIBrowser without setting any "minimize" property (default value is true), but Chrome won't stay minimized. The chrome window only gets minimized after the session is correctly initiated.

I don't know if this is a bug or if this is working as intended... So my question is: Is there any way to change the code so that Chrome stays *always* minimized and out of view?

**Comment by transitive-bullshit** [comment]
Great question; which platform are you on btw?

I've been annoyed with this as well on macOS, and it looks like you can set a plist property to ensure that window activity always stays in the background, but that's pretty messy.. if anyone has a better solution, I'm all ears.

I think part of the reason we're not minimizing right away is because the captcha stuff used to be a lot less robust, so I always wanted to watch it do it's thing, but I think it's robust enough at this point to leave minimized for that.

**Comment by B1LDER** [comment]
I'm on Windows 11, and the captcha thing usually works quite good (specially for cloudflare, less so for nopecha but still ok).
I don't know anything about plist properties though - could that work for Windows? Or is there any puppeteer parameter that could help?
