### ISSUE TITLE
why browser not closed

### ISSUE THREAD

**Issue by dreamfly32** [transitive-bullshit/chatgpt-api#255]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node v18.13.0

### Describe the Bug

when i successfully log in to openai, the browser not closed, why? it takes up a lot of memory
in addition, please give all page goto,waitForSelector add custom timeout ，this is useful on low memory  and low cpu machine when network is slow.
thanks！

**Comment by transitive-bullshit** [comment]
> when i successfully log in to openai, the browser not closed, why? it takes up a lot of memory

That's how this package works at the moment. We need to create HTTP requests _from within the browser's page_ so the TLS fingerprint and environment matches the official webapp as closely as possible. Otherwise, Cloudflare will notice something is up.

It is possible, however, to get around this using https://github.com/bogdanfinn/tls-client to spoof the TLS fingerprint, but this hasn't been implemented into the project yet, and I have mixed feelings about whether I want to since it adds quite a bit of complexity.
