### ISSUE TITLE
Openai and chatgpt are not the same thing

### ISSUE THREAD

**Issue by leungMr** [transitive-bullshit/chatgpt-api#314]
### Describe the feature

I think the key applied in openai should not have the same interface as chatgpt. What do you think?

**Comment by transitive-bullshit** [comment]
Agreed.

This package has gone through many iterations, and you can still use `v3` which is a browser wrapper around accessing the ChatGPT web UI directly.

We moved to using the OpenAI completions API for three main reasons:

1. We've been able to use stealth, fine-tuned chat models for most of the time since the switch (though OpenAI keeps disabling them)
2. For most people, the difference was negligible
3. The browser-based solution was painful to maintain

The goal, of course, is to have 1:1 parity with ChatGPT, and for that we're still waiting for the official API to be released. Hopefully soon. Until then, we'll be doing the best we can to provide a ChatGPT wrapper ideally using a fine-tuned chat model, but OpenAI disabled it earlier today and we're still looking for a workaround.

**Comment by leungMr** [comment]
Thank you for your reply!
V3 version requires login, but my login IP is disabled, so I can't use it...
Do you still have the original version? Only sessionToken is needed. Can it be used now？

**Comment by transitive-bullshit** [comment]
> Thank you for your reply! V3 version requires login, but my login IP is disabled, so I can't use it... Do you still have the original version? Only sessionToken is needed. Can it be used now？

No; that version stopped working once OpenAI added Cloudflare protections.

**Comment by leungMr** [comment]
I also want to ask, is the key applied from openAi charged according to the usage?
