### ISSUE TITLE
Handle response timeouts

### ISSUE THREAD

**Issue by keleko34** [transitive-bullshit/chatgpt-api#33]
Sometimes the request will freeze and never finish, might be useful to have a timeout in ms attribute.

**Comment by transitive-bullshit** [comment]
Agreed.

In the meantime, see my example here for how to do this on your end: https://github.com/transitive-bullshit/chatgpt-api/issues/16#issuecomment-1338985001

**Comment by transitive-bullshit** [comment]
If anyone's able to debug what's actually going on when this happens, that'd be really helpful btw.

**Comment by transitive-bullshit** [comment]
I was initially reluctant to add timeout support to the package, because you could do it externally as I showed in https://github.com/transitive-bullshit/chatgpt-api/issues/16#issuecomment-1338985001.

I changed my mind, however, and added support for an optional `timeoutMs` parameter in https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v2.0.0

I made this change for two main reasons:

1. Timeouts seem to be happening fairly commonly. I'm not sure if this is just because OpenAI's servers are being overloaded or because of possible rate-limiting, but it's a common enough issue that many people are running into that I felt it could be solved better in the package itself.
2. Currently, it'd be difficult to abort the underlying HTTP `fetch` request upon a timeout. By moving this logic inside of the `sendMessage` function, it's easy to make sure the HTTP `fetch` call gets properly aborted and cleaned up if a timeout occurs.
