### ISSUE TITLE
How to return by word like the official stream

### ISSUE THREAD

**Issue by HttpStatusOK** [transitive-bullshit/chatgpt-api#343]
### Describe the feature

current：
- How
- How can
- How can I 
- How can I help
- How can I help you?

official：
- How
-  can
-  I
-  help
-  you?

**Comment by transitive-bullshit** [comment]
This isn't how the actual stream is returned by OpenAI for ChatGPT (`ChatGPTUnofficialProxyAPI`).

For the completions API (`ChatGPTAPI`), it does return this info for each `onProgress` call, but we're currently appending the text together since it won't always be nice word boundaries, but rather arbitrary token boundaries.

To get what you want, use the `detail` object of the argument passed to your `onProgress` handler, which contains the full OpenAI fetch SEE event details.
