### ISSUE TITLE
TypeError: terminated

### ISSUE THREAD

**Issue by kongleeme** [transitive-bullshit/chatgpt-api#349]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node version 18.4

### Describe the Bug

<img width="680" alt="image" src="https://user-images.githubusercontent.com/12163733/219295343-c8fd572f-7279-4b83-807a-44be8a4b2e21.png">

**Comment by transitive-bullshit** [comment]
@kongleeme is this happening every time for you, and does this happen with the included demos (`demos/demo.tsx`)?

Network / socket errors will happen sometimes due to the nature of unstable internet connections and routers. I recommend using a solution like https://github.com/sindresorhus/p-retry, using `timeoutMs`, and wrapping your calls to `sendMessage` in a `try / catch` block since you may need to occasionally retry requests.

**Comment by kongleeme** [comment]
> @kongleeme is this happening every time for you, and does this happen with the included demos (`demos/demo.tsx`)?
> 
> Network / socket errors will happen sometimes due to the nature of unstable internet connections and routers. I recommend using a solution like https://github.com/sindresorhus/p-retry, using `timeoutMs`, and wrapping your calls to `sendMessage` in a `try / catch` block since you may need to occasionally retry requests.

I have set timeoutMs and haven't reported this problem for the time being，Thanks！
