### ISSUE TITLE
This is fake!

### ISSUE THREAD

**Issue by Xanderplayz16** [transitive-bullshit/chatgpt-api#351]
### Describe the feature

This clearly uses davinci model in src/chatgpt-api.ts , as you can see on line 11 and 12,
`// Official model (costs money and is not fine-tuned for chat)
const CHATGPT_MODEL = 'text-davinci-003'`.
Why?
(davinci model aint chatgpt)

**Comment by transitive-bullshit** [comment]
It is not fake; the current version does use `text-davinci-003`, but there are other options available.

This package has gone through many iterations, and you can still use `v3` which is a browser wrapper around accessing the ChatGPT web UI directly.

We moved to using the OpenAI completions API for three main reasons:

1. We've been able to use stealth, fine-tuned chat models for most of the time since the switch (though OpenAI keeps disabling them)
2. For most people, the difference was negligible
3. The browser-based solution was difficult to use consistently and painful to maintain

The goal, of course, is to have 1:1 parity with ChatGPT, and for that we're still waiting for the official API to be released. Hopefully soon. Until then, we'll be doing the best we can to provide a ChatGPT wrapper ideally using a fine-tuned chat model, but OpenAI disabled it earlier today and we're still looking for a workaround.

**Comment by Xanderplayz16** [comment]
Ohh...

**Comment by transitive-bullshit** [comment]
@Xanderplayz16 also check out the latest release; `ChatGPTUnofficialProxyAPI` is probably what you're looking for.
