### ISSUE TITLE
nodejs ts uses commonjs mode to import chatgpt error

### ISSUE THREAD

**Issue by Child-Cheng** [transitive-bullshit/chatgpt-api#380]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

nodejs:v16.15.1

### Describe the Bug

use guide
```
async function initChatGPT() {
  // To use ESM in CommonJS, you can use a dynamic import
  // const { ChatGPTAPI } = await import('chatgpt');
  // const api = new ChatGPTAPI({ apiKey: config.onpen_token, debug: false });
  const { ChatGPTAPI, ChatGPTUnofficialProxyAPI } = await import('chatgpt');
  const api = config.open_ai_type
    ? new ChatGPTUnofficialProxyAPI({
        accessToken: config.onpen_token,
        debug: false,
      })
    : new ChatGPTAPI({ apiKey: config.onpen_token, debug: false });
  global.chatGPTAPI = api;
}

```
Error message：to a dynamic import() which is available in all CommonJS modules.
start method：ts-node --files app.ts

**Comment by transitive-bullshit** [comment]
CommonJS issues are outside the scope of this repo, and there's a good reason we're not supporting it.

I recommend that you ask your question on StackOverflow. Also search through the existing issues since other folks have asked very similar questions already.

You may have better luck compiling to JS first or using `tsx` instead of `ts-node`. There could be a problem with your `tsconfig`. Lots of possible problems – all of which are outside of this package unfortunately.
