### ISSUE TITLE
Next 13.2 new route handler bug

### ISSUE THREAD

**Issue by brunoocal** [transitive-bullshit/chatgpt-api#413]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

NodeJS v19.0.1
Browser: Irrelevant
OS: Windows 11

### Describe the Bug

Console throws this. My route handler is just an instance of ChatGPTAPI (official API) sending the text of a sendMessage() call.

![image](https://user-images.githubusercontent.com/75707587/222325353-951e8c2e-c0a3-4426-965f-88b530cda6e1.png)

**Comment by transitive-bullshit** [comment]
@brunoocal what `keyv` and `keyv` adaptor(s) are you using?

This was a known bug in `keyv` awhile back, but it should've been fixed in https://github.com/jaredwray/keyv/pull/119

**Comment by brunoocal** [comment]
None

**Comment by transitive-bullshit** [comment]
Okay; let me investigate a bit..

**Comment by transitive-bullshit** [comment]
@brunoocal just to try and repro, are you using `appDir`? and which package manager?

**Comment by brunoocal** [comment]
Yes, It's in the appDir new route handler in Next 13.2 with latest npm version. I just tried the same code in pages/api and works perfectly

**Comment by transitive-bullshit** [comment]
Yeah; I'm able to repro it using next 13.2 w/ a route handler.

My suggestion for now would be to:

1. Open a bug report on the next.js repo, since `keyv` is a pretty common NPM module, and their `route` handlers should support it without errors
2. Use a `pages/api` handler for now until Next.js 13's beta features are more stable

If you end up creating an issue on the next.js repo, please link it to here so we can track progress.

Thanks!

**Comment by brunoocal** [comment]
Thank you!
