### ISSUE TITLE
error: either set OPENAI_API_KEY or use --apiKey

### ISSUE THREAD

**Issue by LifeNT** [transitive-bullshit/chatgpt-api#428]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

wsl2, win11, unbuntu22,

### Describe the Bug

I have set set OPENAI_API_KEY, when run npx chatgpt, I get this:
error: either set OPENAI_API_KEY or use --apiKey

**Comment by transitive-bullshit** [comment]
Does it work when setting it explicitly via `--apiKey`?

Can you confirm that `OPENAI_API_KEY` is set correctly via `env` before running `npx chatgpt@latest`?

I'm not able to repro any issues with the CLI locally or via CI.

**Comment by Bahlinc-Dev** [comment]
I get this too, same env as OP, but works within a node script.   So this is just something with the CLI.   If I use the --apiKey flag it returns 401

**Comment by pui30576** [comment]
My environment is wsl2, win10, ubuntu.
The `--apiKey` option flag doesn't work, but fine with the env method, 
Hope this help.
```
export OPENAI_API_KEY="sk-TODO"
npx chatgpt "your prompt here"
```

**Comment by transitive-bullshit** [comment]
@pui30576 I'm not sure if `export OPENAI_API_KEY="sk-TODO"` is how you set a persistent environment variable for your shell / OS. This is just how you do it in some shells.

A few things you can do to try and resolve this issue, since this seems to only repro on the specific combination of `wsl2`, `win10`, `ubuntu`:

1. I just pushed a fix to the `--apiKey` parameter if you upgrade to latest.
2. Try `npm i -g chatgpt@latest` and then run `chatgpt "example"`. Maybe `npx` on your system isn't properly propagating the environment variables.

**Comment by transitive-bullshit** [comment]
Closing as `--apiKey` was fixed in the latest release. If you figure out why the environment variable isn't working in your env, please let us know.

Thanks!
