### ISSUE TITLE
Use edit models?

### ISSUE THREAD

**Issue by Naozumi520** [transitive-bullshit/chatgpt-api#440]
### Describe the feature

How can I use the edit model? I filled in `text-davinci-edit-001` and it returns `statusText: 'Not Found'`.

**Comment by huluohu** [comment]
> ### Describe the feature
> How can I use the edit model? I filled in `text-davinci-edit-001` and it returns `statusText: 'Not Found'`.

There really is no this model!

**Comment by Naozumi520** [comment]
My bad, the stable model is 003, not 001.

**Comment by Naozumi520** [comment]
Wait, even 003 is not working.

**Comment by transitive-bullshit** [comment]
@Naozumi520 `ChatGPTAPI` only supports [chat completion models](https://platform.openai.com/docs/api-reference/chat).

All of the models you're trying to use are the old non-chat completion models.

OpenAI recommends using the chat-specific models because they are cheaper and higher quality than, for instance, `text-davinci-003`. The old edit models are not supported.
