### ISSUE TITLE
The maximum context length is incorrectly configured for the official ChatGPT API

### ISSUE THREAD

**Issue by SimonBaars** [transitive-bullshit/chatgpt-api#442]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Library version: 5.0.6

Node version: 19.7.0

OS: Arch Linux

### Describe the Bug

When I have very long conversations with the API, I get a lot of errors like this one:
```
Error: OpenAI error 400: {
  "error": {
    "message": "This model's maximum context length is 4096 tokens. However, you requested 4119 tokens (3119 in the messages, 1000 in the completion). Please reduce the length of the messages or completion.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  }
}
```

I have the feeling that the internal context kept by the `chatgpt-api` is incorrectly configured for this model.

**Comment by HttpStatusOK** [comment]
我也有同样的问题 🤦‍♂️

**Comment by transitive-bullshit** [comment]
For now, as a workaround, set `maxModelTokens` to 4000 in the constructor as a workaround.

This is happening because we're using an **estimate of the token length**, and there currently is not way to reliably determine the actual token length of the combined `messages` that we pass to the OpenAI chat completions API.

See also #438

**Comment by transitive-bullshit** [comment]
The latest update sets a more conservative `maxModelTokens`, which should help mitigate this error: https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v5.0.8

It's unfortunately not possible to completely remove the possibility for this error at the moment, because we don't have access to how OpenAI's chat endpoint is calculating token lengths for the `messages`, so we're currently using an estimate.

**Comment by transitive-bullshit** [comment]
Closing as [v5.0.8 (release)](https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v5.0.8) contains a suitable temporary fix.
