### ISSUE TITLE
identify http request from unauthorized regions now allowed by openAI

### ISSUE THREAD

**Issue by jzhao62** [transitive-bullshit/chatgpt-api#481]
### Describe the feature

- we should block access from regions such as, but not limited to china, russia,
- reference here https://platform.openai.com/docs/supported-countries
- this also protect users from these contries from having their account suspended, and addressing some legal concerns for this repository

**Comment by transitive-bullshit** [comment]
this is just a wrapper around the openai api; we will not enforce anything on our end because:

1. openai already enforces things in their api which we're calling
2. this is well beyond the scope of what this library should be aware of or responsible for
3. these things are subject to change and the last thing this library should be doing is worrying about different IP regions
4. it's extremely easy to proxy to a different region, so there's almost no point in trying to enforce something like this

this is well outside the scope of what any wrapper library like this should be responsible for, and ultimately it's up to openai's api to enforce (though in practice, it's mostly impossible to enforce effectively at scale)
