### ISSUE TITLE
Quietly exit for no reason

### ISSUE THREAD

**Issue by dany-nonstop** [transitive-bullshit/chatgpt-api#54]
Thanks for making the API, it works pretty well until a very annoying bug surfaces:

if you make multiple queries consecutively, after about several queries, calling `api.sendMessage()` would exit without the program any error output at the console.

I'm using node v16.18.1, if that matters.

**Comment by dany-nonstop** [comment]
After some tests, it seems when I have too many requests, it will also exit without any prompt -- though the error will be visible if I try ChatGPT's  web interface. It'll state: "Too many requests in 1 hour. Try again later." It would be nice to have these error messages also returned to the user as exception, for example.

**Comment by transitive-bullshit** [comment]
Can you provide a code snippet of how you are invoking `api.sendMessage`? And also include the output `stdout` and `stderr`?

> if you make multiple queries consecutively, after about several queries, calling api.sendMessage() would exit without the program any error output at the console.

There really shouldn't be any way for this library to exit the process. The only real result I can potentially see is that an `Error` is thrown and you're not handling it, and for some reason the process' stderr isn't displaying that error / stack trace to you. Really depends on your environment, though.

**NOTE**: I strongly recommend against having multiple `api.sendMessage` calls running concurrently. While it may be possible and work for a bit, this will severely degrade the robustness of your program since the current unofficial API isn't really meant to be used this way. I recommend adding a reasonable [delay](https://github.com/sindresorhus/delay) in between `sendMessage` calls to mitigate rate limits.

Here are a few of the special responses I'm looking for from chatgpt: https://github.com/transitive-bullshit/chatgpt-twitter-bot/blob/main/src/respond-to-new-mentions.ts#L258-L269

**Comment by dany-nonstop** [comment]
Thanks for looking at the problem. The code is very straightforward, there is no concurrent execution, however after some time it will just stop with nothing to report

```javascript
for (var uid of uids) {
    prompt = 'Generate a summary of the the article\n\n' + text
    response = await api.sendMessage(prompt) //, {conversationId: uid})
    console.log(new Date().toLocaleTimeString() + ' uid ' + result.uid)
}
```
output
```
$ node test.js
...
11:58:09 PM uid 151
11:58:49 PM uid 152
```
with no error message nothing, and I have many more items in array `uids`. I can however resume from uid 153 after an hour. So i believe it's chatgpt-api's problem. It doesn't recognize the error and quietly exit.

**Comment by transitive-bullshit** [comment]
@dany-nonstop let me know if there's anything else I can to to try and help. Otherwise, I'm closing this as it doesn't seem to be affecting other people.

Thanks

**Comment by dany-nonstop** [comment]
Thank you @transitive-bullshit it's still there, the smallest I can repeat is this, if it helps you debug. I'm already adding 60s between calls. It just stays there.


```javascript
async function extract() {
  for (var row of content) {
    prompt = 'summarize this paragraph \n\n' + row
    response = await api.sendMessage(prompt)
  }
}
```
