### ISSUE TITLE
This browser or app may not be secure.

### ISSUE THREAD

**Issue by BigWings2020** [transitive-bullshit/chatgpt-api#6]
When trying to log in with Google I get...

This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.

**Comment by transitive-bullshit** [comment]
The browser is using Playwright, which since it's super customizable and scriptable is "not secure" by design. See https://github.com/microsoft/playwright/issues/3060 if this is preventing you from logging in. Otherwise, this is expected.

Note that the headless browser approach will be going away soon.

**Comment by BigWings2020** [comment]
Thanks, I'll have a look

**Comment by transitive-bullshit** [comment]
v1.0.0 removes the browser in favor of using the unofficial REST API, so this should no longer be a concern. https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v1.0.0
